config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options

  post 'image_dropzone/upload'

  # FIXME(uwe): Separate to MyAttendanceController
  get 'mitt/oppmote(/:reviewed_attendance_id)' => 'attendances#plan', as: :attendance_plan
  get 'attendances/plan' # must be after "mitt/oppmote"
  post 'attendances/announce(/:year/:week/:group_schedule_id)/:status(/:user_id)' =>
      'attendances#announce', as: :announce_attendance
  # EMXIF

  get 'map' => 'map#index'
  get 'search' => 'search#index'
  post 'send_grid/receive' => 'send_grid#receive'
  get 'svar/:id', controller: :survey_requests, action: :answer_form
  patch 'svar/:id', controller: :survey_requests, action: :save_answers
  post 'svar/:id', controller: :survey_requests, action: :save_answers
  get 'takk/:id', controller: :survey_requests, action: :thanks
  get 'velkommst' => 'welcome#front_parallax', as: :front_parallax

  resources :application_image_sequences
  resources :application_steps do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :application_videos
  resources :appointments
  resources :annual_meetings
  scope controller: :attendance_form, path: 'oppmøte/skjema' do
    root action: :index, as: :attendance_forms
    get ':year/:month/:group_id', action: :show, as: :attendance_form
  end
  resources :attachments, only: :destroy
  resources :attendances do
    collection do
      get :history_graph, action: :history_graph
      get :history_graph_data, action: :history_graph_data
      get 'month_chart(/:year/:month)', action: :month_chart, as: :month_chart
      get 'month_chart_data(/:year/:month)', action: :month_chart_data, as: :month_chart_data
      get 'month_per_year_chart(/:month)', action: :month_per_year_chart, as: :month_per_year_chart
      get 'month_per_year_chart_data(/:month)', action: :month_per_year_chart_data,
          as: :month_per_year_chart_data
      get 'report(/:year/:month)', action: :report, as: :report
      match 'review/:year/:week/:group_schedule_id/:status(/:user_id)', action: :review,
          via: %i[get post]
      get :since_graduation
    end
    member do
      get :practice_details
    end
  end
  resources :attendance_notifications, only: :index do
    collection do
      post :push
      post :subscribe
    end
  end
  resources :attendance_webpushes
  get 'audit/index/:item_type/:item_id' => 'audit#index', as: :audit
  resources :basic_techniques
  resources :birthday_celebrations do
    member { get :certificates }
  end
  resources :board_meetings do
    member do
      get :minutes
    end
  end
  resources :card_keys
  resources :censors do
    match :accept, on: :member, via: %i[get post] # GET from emails
    match :decline, on: :member, via: %i[get post] # GET from emails
  end

  resources :correspondences
  resources(:curriculums, path: :pensum, only: %i[index show]) { collection { get :card_pdf } }
  resources(:curriculum_groups)
  resources :elections
  resources :embus do
    member do
      get :print
    end
  end
  resources :embu_images
  resources :embu_part_videos
  resources :embu_parts
  resources :event_invitee_messages
  resources :event_invitees
  resources :event_registration, path: 'event/registration' do
    member do
      post :accept
      post :decline
      get :will_work
      get :will_not_work
    end
  end
  resources :event_messages do
    collection do
      get :template
    end
  end
  resources :events do
    collection do
      get :attendance_form
      get :calendar
      post :preview
    end
    member do
      post :add_org
      post :accept
      get :calendar
      post :decline
      post :invite
      get :preview
      patch :preview
      post :preview
      get :tentative
    end
  end
  resources :external_events do
    member do
      post :accept
      post :decline
    end
  end

  resources :front_page_sections
  resources :graduates do
    member do
      match :accept, via: %i[get post] # GET from emails
      match :decline, via: %i[get post] # GET from emails
    end
  end
  resources :graduations do
    member do
      post :accept
      patch :add_group
      post :approve
      get :censor_form
      get :censor_form_pdf
      get :certificates
      post :decline
      post :disapprove
      get 'graduates_list/:section', action: :graduates_list, as: :graduates_list
      post :lock
      patch :send_date_change_message
      get :tentative
    end
  end
  resources :group_instructors
  resources :group_schedules
  resources :group_semesters
  resources :groups

  get 'icon/notification' => 'icons#notification_icon'
  get 'icon/:width' => 'icons#inline'

  resources :images do
    member do
      get :gallery
      get :blurred
      get 'inline(/:width).:format', action: :inline, as: :inline
      get 'show(/:width).:format', action: :show, as: :show
      patch :reset_google_drive_reference
    end
    collection do
      get :gallery
      get :mine
      post :upload
      get 'inline/:id(/:width).:format', action: :inline
      get 'show/:id(/:width).:format', action: :show
    end
  end
  resources :information_pages, controller: :info, path: :info do
    collection { post :preview }
    member do
      get :move_up
      get :move_down
      patch :preview
    end
  end
  resources :instructor_meetings do
    member do
      post :accept
      post :decline
    end
  end

  controller :login do
    match 'login/change_password', action: :change_password, via: %i[get post], as: :change_password
    match 'login/forgot_password', action: :forgot_password, via: %i[get post], as: :forgot_password
    get 'login/link_message_sent', action: :login_link_message_sent, as: :login_link_message_sent
    match 'login/password', action: :login_with_password, via: %i[get post], as: :login_password
    match 'login/signup', via: %i[get post]
    get 'login/welcome'
    get 'login', action: :login_link_form, as: :login
    post 'login', action: :send_login_link, as: :send_login_link
    get 'logout', action: :logout, as: :logout
  end

  resources(:martial_arts) { member { post :copy } }

  controller :member_reports do
    get 'member_reports', action: :index
    get 'member_reports/age_chart', action: :age_chart, as: :member_reports_age_chart
    get 'member_reports/age_chart_data', action: :age_chart_data, as: :member_reports_age_chart_data
    get 'member_reports/grade_history_graph(/:size)', action: :grade_history_graph,
        as: :member_reports_grade_history_graph
    get 'member_reports/grade_history_graph_data', action: :grade_history_graph_data,
        as: :member_reports_grade_history_graph_data
    get 'member_reports/grades_graph_data', action: :grades_graph_data,
        as: :member_reports_grades_graph_data
    get 'member_reports/history_graph(/:size)', action: :history_graph,
        as: :member_reports_history_graph
    get 'member_reports/history_graph_data', action: :history_graph_data,
        as: :member_reports_history_graph_data
  end

  resources :members do
    collection do
      get :email_list
      get :excel_export
      get :list_active
      get :list_inactive
      get :telephone_list
      get :trial_missing_contract
    end
    member do
      get :image
      get :missing_contract
      get :photo
      post :save_image
      get :since_graduation
      get :thumbnail
    end
  end

  resources :news_item_likes

  resources :news_items, controller: :news, path: :news do
    collection do
      get :list
      post :preview
    end
    member do
      post :expire
      post :like
      post :move_to_top
      patch :preview
    end
  end

  resources :nkf_members do
    collection do
      get :sync_errors
      get :sync_progress
      post :sync_with_nkf
    end
  end
  resources :nkf_member_trials do
    collection do
      get :sync_progress
      post :sync_with_nkf
    end
  end
  resources :page_aliases
  resources :practices
  resources :price_age_groups
  resources :public_records
  resources :rank_articles
  resources :ranks do
    member do
      get :card
      get :card_pdf
      get :pdf
    end
  end
  resources :roles do
    member do
      get :move_up
      get :move_down
    end
  end
  resources :semesters
  resources :signatures do
    member do
      get :image
    end
  end

  scope controller: :signup_guide, as: :signup_guide, path: 'innmelding' do
    root action: :basics
    match :basics, via: %i[get post]
    match :contact_info, via: %i[get post]
    match :guardians, via: %i[get post]
    match :groups, via: %i[get post]
    post :complete
    patch :complete
    get :find_user
  end

  resources :signups do
    member do
      patch :complete
      delete :terminate
    end
  end
  resources :sms, only: %i[index show create]

  controller :status do
    get 'status', action: :index
    get 'status/health', action: :health
  end

  resources :survey_answer_translations
  resources :survey_answers
  resources :survey_questions
  resources :survey_requests
  resources :surveys
  resources :technique_applications do
    member do
      post :move_down
      post :move_up
    end
  end
  resources :technique_links
  resources :user_images, only: [] do
    member do
      post :like
    end
  end
  resources :user_merge, only: %i[show update]
  resources :user_messages
  resources :users do
    member do
      post :change_password
      post :forgot_password
      patch :move_attribute
      get :photo
      patch :restore
      get :valid
    end
  end

  resources :wazas

  draw_drilldown :member_drilldown
  draw_drilldown :user_drilldown

  root to: 'welcome#index'

  get 'documents/*path_info', controller: :documents, action: :webdav
end

app/models/survey.rb
# frozen_string_literal: true

class Survey < ApplicationRecord
  acts_as_list

  has_many :survey_questions, dependent: :destroy
  has_many :survey_requests, dependent: :destroy
  has_many :members, through: :survey_requests

  def included_members
    Member.active.includes(:user).references(:users)
        .where('users.birthdate IS NOT NULL AND birthdate <= ?', Member::JUNIOR_AGE_LIMIT.years.ago)
  end

  def pending_members
    survey_requests.pending.map(&:member)
  end

  def completed_members
    survey_requests.completed.map(&:member)
  end

  def ready_members
    included_members.order(:joined_on) - pending_members - completed_members
  end
end

app/controllers/surveys_controller.rb
# frozen_string_literal: true

class SurveysController < ApplicationController
  before_action :admin_required
  before_action :set_survey, only: %i[show edit update destroy]

  def index
    @surveys = Survey.all
  end

  def show; end

  def new
    @survey = Survey.new
  end

  def edit; end

  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey = Survey.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def survey_params
    params.require(:survey)
        .permit(:category, :group_id, :title, :position, :expires_at, :header, :footer)
  end
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
    <% if @survey.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this
            survey from being saved:</h2>

          <ul>
            <% @survey.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, 'Tittel (vises i e-post og svarsiden.)' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :category, 'Kategori (aktiv/passiv/utmeldt)' %>
          <%= f.text_field :category, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :group_id %>
          <%= f.number_field :group_id, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :position %>
          <%= f.number_field :position, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :expires_at %>
          <%= f.text_field :expires_at, class: 'form-control datetime' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :header, 'Innledning (vises i e-post og svarsiden)' %>
      <%= f.text_area :header, class: 'form-control expanding' %>
    </div>
    <div class="form-group">
      <%= f.label :footer, 'Oppsummering (vises etter besvarelse)' %>
      <%= f.text_area :footer, class: 'form-control expanding' %>
    </div>

    <div class="actions">
      <%= f.submit 'Lagre', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/surveys/edit.html.slim
h1 Endre spørreundersøkelse

= render 'form'

h3.mt-3 Spørsmål

table.table
  - @survey.survey_questions.sort_by(&:position).each do |question|
    tr
      td
        = question.title
        .help-block = question.choices
      td =link_to 'Endre', edit_survey_question_path(question), class: 'btn btn-secondary'

.float-right
  = back_or_link_to 'Tilbake', surveys_path, class: 'btn btn-secondary mr-2'
  = link_to 'Vis', @survey, class: 'btn btn-secondary mr-2'
  = link_to 'Legg til spørsmål', \
        new_survey_question_path(survey_question: {survey_id: @survey.id}), \
        class: 'btn btn-primary'

app/views/surveys/index.html.slim
- @content_width = 1024

= link_to 'New Survey', new_survey_path, class: 'btn btn-primary float-right'

h1 Listing surveys

table.table.table-hover
  thead
    tr
      th #
      th Title
      th Header
      th Footer
      th Category
      th Group
      th Expires at
      th
  tbody
    - @surveys.each do |survey|
      tr record-id=survey.id style="cursor: pointer"
        td = survey.position
        td = survey.title
        td = survey.header
        td = survey.footer
        td = survey.category
        td = survey.group_id
        td = survey.expires_at
        td
          = link_to 'Show', survey, class: 'btn btn-secondary'
          = link_to 'Edit', edit_survey_path(survey), class: 'btn btn-secondary'
          = link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

javascript:
  $('tr[record-id]').on('click', function(){
      record_id = $(this).attr('record-id');
      window.location = '#{surveys_path}/' + record_id;
  });

app/views/surveys/new.html.erb
<h1>Ny spørresundersøkelse</h1>

<%= render 'form' %>

<%= link_to 'Tilbake', surveys_path, class: 'btn btn-secondary' %>

app/views/surveys/show.html.slim
p#notice = notice

.row
  .col-md-3
    strong Kategori:
    = @survey.category
  .col-md-3
    strong Gruppe:
    = @survey.group_id
  .col-md-3
    strong Posisjon:
    = @survey.position
  .col-md-3
    strong Utgår:
    = @survey.expires_at

h3.mt-3 Overskrift:
h4 = @survey.title

h3.mt-3 Innledning:
= @survey.header

h3.mt-3 Spørsmål

- @survey.survey_questions.order(:position).each do |sq|
  p
    div = sq.title
    - answer_hash = Hash.new(0)
    - sq.survey_answers.map(&:answers).each do |answers|
      - answers.each{|k,v| answer_hash[k] += 1}
    - answer_hash = answer_hash.sort_by(&:second).reverse
    - answer_hash.each do |answer, count|
      span.badge.badge-info> = "#{answer}: #{count}"
    = pie_chart answer_hash

.row
  .col-md-12
    h3 Avslutning:
    = @survey.footer

.mt-3
  = link_to :Tilbake, surveys_path, class: 'btn btn-link'
  = link_to :Rediger, edit_survey_path(@survey), class: 'btn btn-primary'

table.table.table-sm.mt-3
  thead
    tr
      th Navn
      th Innmeldt
      th Aktiv
      th Spurt
      th Minnet på
      th Fullført
      th Svar
  tbody
    - (@survey.included_members.select(&:active?) + @survey.survey_requests.map(&:member)).uniq.sort_by(&:joined_on).reverse.each do |m|
      - survey_request = @survey.survey_requests.find { |sr| sr.member_id == m.id }
      tr
        td = m.name
        td = m.joined_on
        td = m.active? ? :Ja : :Nei
        td = survey_request&.sent_at&.to_date
        td = survey_request&.reminded_at&.to_date
        td = survey_request&.completed_at&.to_date
        td
          - if survey_request&.survey_answers&.size&.positive?
            = link_to survey_request.survey_answers.size, survey_request